import React, { ReactNode } from 'react';
import Head from 'next/head'
import type { NextPage } from 'next'
import Image from 'next/image'
import { HomeComponent } from '../components/home/home-component'
import styles from '../styles/Home.module.css'
import { LayoutsHeader } from './header/layouts-header.component';
import { LayoutsFooter } from './footer/layouts-footer.component';


interface ILayoutsMain {
    title: string;
    children?: ReactNode;
    page: string;
}

export const LayoutsMain: React.FC<ILayoutsMain> = (props: ILayoutsMain) => {
    return (
        <div>
            <Head>
                <title>Tempora {props.title ? ` | ${props.title}` : ''}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <LayoutsHeader />
            <main>
                {props.children}
            </main>
            <LayoutsFooter />
        </div>
    )
}